from __future__ import annotations

import json
import logging
from dataclasses import asdict
from datetime import datetime
from pathlib import Path

from convaier.context import PipelineContext

log = logging.getLogger("convaier")


def _render_markdown(ctx: PipelineContext) -> str:
    lines = [
        "# Convaier Pipeline Report",
        f"**Project**: {ctx.config.project_name} | "
        f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | "
        f"**Result**: {'PASSED' if not ctx.errors else 'FAILED'}",
        "",
    ]

    # Timings
    if ctx.timings:
        lines.append("## Timings")
        for stage, t in ctx.timings.items():
            lines.append(f"- **{stage}**: {t:.1f}s")
        lines.append("")

    # Commit
    if ctx.changed_files:
        lines.append("## Commit")
        lines.append(f"- Changed files: {len(ctx.changed_files)}")
        for f in ctx.changed_files[:20]:
            lines.append(f"  - `{f}`")
        lines.append("")

    # Lint
    if ctx.lint_results:
        lines.append("## Lint")
        lines.append("| Tool | File | Line | Message |")
        lines.append("|------|------|------|---------|")
        for issue in ctx.lint_results[:50]:
            lines.append(f"| {issue.tool} | `{issue.file}` | {issue.line} | {issue.message} |")
        lines.append("")

    # Security
    if ctx.security_issues or ctx.security_ai_comments:
        lines.append("## Security")
        if ctx.security_issues:
            lines.append("### Tool Findings")
            lines.append("| Tool | File | Line | Severity | CWE | Message |")
            lines.append("|------|------|------|----------|-----|---------|")
            for issue in ctx.security_issues[:50]:
                cwe = f"CWE-{issue.cwe}" if issue.cwe else "-"
                lines.append(f"| {issue.tool} | `{issue.file}` | {issue.line} | {issue.severity} | {cwe} | {issue.message} |")
            lines.append("")
        if ctx.security_ai_comments:
            lines.append("### AI Analysis")
            for c in ctx.security_ai_comments:
                loc = f"`{c.file}:{c.line}`" if c.line else f"`{c.file}`"
                lines.append(f"#### {loc} [{c.severity}]")
                lines.append(f"> {c.message}")
                lines.append("")
        lines.append("")

    # Review
    if ctx.review_comments:
        lines.append("## Code Review (AI)")
        for c in ctx.review_comments:
            loc = f"`{c.file}:{c.line}`" if c.line else f"`{c.file}`"
            lines.append(f"### {loc} [{c.severity}]")
            lines.append(f"> {c.message}")
            lines.append("")

    # Metrics
    if ctx.metrics_result:
        mr = ctx.metrics_result
        lines.append("## Code Metrics")
        lines.append(f"- **Average complexity**: {mr.avg_complexity}")
        lines.append(f"- **Average maintainability**: {mr.avg_maintainability}")
        lines.append(f"- **Total LOC**: {mr.total_loc}")
        if mr.coverage is not None:
            lines.append(f"- **Test coverage**: {mr.coverage}%")
        lines.append("")
        if mr.files:
            lines.append("| File | Complexity | Maintainability | LOC |")
            lines.append("|------|-----------|-----------------|-----|")
            for fm in mr.files:
                lines.append(f"| `{fm.file}` | {fm.complexity} | {fm.maintainability} | {fm.loc} |")
            lines.append("")
        if mr.ai_recommendations:
            lines.append("### AI Recommendations")
            for r in mr.ai_recommendations:
                lines.append(f"- {r}")
            lines.append("")

    # Tests
    if ctx.test_results:
        tr = ctx.test_results
        lines.append("## Tests")
        lines.append(f"- {tr.passed} passed, {tr.failed} failed, {tr.skipped} skipped")
        if tr.duration:
            lines.append(f"- Duration: {tr.duration:.1f}s")
        lines.append("")

    # Build
    if ctx.build_result:
        br = ctx.build_result
        status = "OK" if br.success else "FAILED"
        lines.append("## Build")
        lines.append(f"- Image: `{br.image}:{br.tag}` — {status} ({br.duration:.1f}s)")
        lines.append("")

    # Deploy
    if ctx.deploy_result:
        dr = ctx.deploy_result
        status = "OK" if dr.success else "FAILED"
        lines.append("## Deploy")
        lines.append(f"- Service `{dr.service}` — {status}")
        lines.append("")

    # Errors
    if ctx.errors:
        lines.append("## Errors")
        for err in ctx.errors:
            lines.append(f"- **{err.stage}**: {err.error}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by convaier*")
    return "\n".join(lines)


def _safe_asdict(ctx: PipelineContext) -> dict:
    d = asdict(ctx)
    # Convert Path objects to strings
    d["project_root"] = str(ctx.project_root)
    return d


def generate_reports(ctx: PipelineContext) -> list[Path]:
    output_dir = Path(ctx.config.reports.output_dir)
    if not output_dir.is_absolute():
        output_dir = ctx.project_root / output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    paths: list[Path] = []
    formats = ctx.config.reports.formats

    if "json" in formats:
        p = output_dir / f"run-{ts}.json"
        data = _safe_asdict(ctx)
        p.write_text(json.dumps(data, indent=2, default=str, ensure_ascii=False), encoding="utf-8")
        paths.append(p)

    if "markdown" in formats:
        p = output_dir / f"run-{ts}.md"
        p.write_text(_render_markdown(ctx), encoding="utf-8")
        paths.append(p)

    return paths
